shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - semver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - prisma
  - unrs-resolver
